### ISSUE TITLE
Error while loading Codes

### ISSUE THREAD

**Issue by Bodyash** [DziNeIT/commandcodes#8]
Hi, i have a BIG problem with your plugin. I cant load any codes. For example - i created few codes, they works pretty good, but after server restart plugin cant load saved codes with that error:

![default](https://cloud.githubusercontent.com/assets/2454569/6492507/bd43bcb4-c2bc-11e4-9d5d-b51c0fcb4b09.PNG)

I tried to compile a new version of your plugin from GitHub, using latest Spigot API(1.8), but this error still here. Can u fix it? Because i`m so bad in Java, so hard to undestand code.
Ty much! And sorry for my bad English

**Comment by Bodyash** [comment]
For the developers out there there is one change that will affect a few NMS plugins and will be useful for Bukkit plugins. The Google Gson library has been moved out of org.bukkit.craftbukkit.libs and instead added to its normal location, as part of the Bukkit API. This means that plugins wishing to use Gson as an advanced JSON reading library may now do so without shading their own copy or using non-api methods.

1.8.3 SPIGOT

**Comment by Bodyash** [comment]
Where i can download new version?

**Comment by DziNeIT** [comment]
@Bodyash it's currently awaiting approval on BukkitDev http://dev.bukkit.org/bukkit-plugins/commandcodes/files/3-command-codes-v1-1-1/

Here's an attached version if you don't want to wait
